export const linking = {
  prefixes: ['syncroflow://', 'exp+syncro-flow://'],
  config: {
    screens: {
      '(tabs)': {
        screens: {
          index: '',
          timeline: 'timeline',
          automations: 'automations',
          add: 'add',
          settings: 'settings',
        },
      },
      Scanner: 'scanner',
      ScannerAction: 'scanner-action',
      ProductDetail: 'product/:id',
      ProductEdit: 'product/edit/:id',
      SettingsLocations: 'settings/locations',
      SettingsFields: 'settings/fields',
      SettingsFolders: 'settings/folders',
      SettingsLayoutBuilder: 'settings/layout-builder',
      SettingsGs1: 'settings/gs1-config',
      SettingsHardware: 'settings/hardware',
      SettingsTrash: 'settings/trash',
      SettingsShare: 'settings/share',
      Audit: 'automations/audit',
      BatchMove: 'automations/batch-move',
      ScanSell: 'automations/scan-sell',
      QuickTag: 'automations/quick-tag',
      AutomationFlow: 'automations/automation-flow/:id',
      CustomRunner: 'automations/custom-runner/:id',
      NotFound: '*',
    },
  },
};
